const chirps = [
"What even is a loft anyway?"
"I'm glad I finally moved out. Cramped and cheap but it's my place now."
"Best part of living in a small apartment is how easy it is to clean!"
"Who's the neighbour with the drums? Shut up already!"
"The right size for the right buck. New place!"
"Who's baking cookies? they smell delicious! May I have some?"
"I kicked my neighbours welcome mat into the elevator pit. Oops."
"I love kicking my neighbours rug."
"Need someone to walk your dogs? Professional Dog Walker for hire! DM for info."
"Anyone know a good Italian place around?"
"Dude, it's just a game, do you need to scream for every goal?"
"Stop screaming the goals you're spoiling me the game!"
"Someone parked on my entrance today, had to take the bus to work."
"Settled and ready to go! Watch out world!"
"My place feels too empty. Where can I get some cool art?"
"I paid for my produce but forgot the bags. I can't go back to that supermarket ever again."
"A car's alarm has been going off for hours! Why do you even bother having one?"
"My key is not working on our building's door. anyone elses?"
"I hope I don’t get sick, I don’t even know where’s the nearest hospital."
"I just need more RydeCola, no need to go see the doc."
"Anyone selling used elementary textbooks for 3rd grade?"
"I can’t find a good place to park with all these bicycles in the way!"
"I’m staying late at work today. The company needs me."
"First day at my new job. Wish me luck!"
"I wonder why I’m training the new guy to do the same work that I do."
"Found a coin! Lucky day!"
"I lost a coin today."
"I’m ordering takeout tonight. Any recommendations?"
"That squirrel looks funny."
"I hate the reception here, Why am I paying 8G for?"
"I shall not step on any floor crack today."
"I haven't been feeling myself lately. I need a long walk."
"Some random said good morning to me today. weirdo."
"She hasn’t texted me back but I know she will."
"He hasn’t texted me back but I know he will."
"They haven’t texted me back but I know they will."
"I do not feel ready to be an adult."
"I wish I could talk to my dog."
"I wish I could talk to my cat."
"I’m not sure if I turned off the stove before leaving."
"I can’t decide what to get for breakfast."
"I can’t decide what to get for lunch."
"I can’t decide what to get for dinner."
"I must not forget to pay my credit card again."
"I just bought a new jacket. I kinda regret the colour."
"I love my new jacket. It is SO me."
"I do not like this song enough to not skip it but I do not dislike it enough to remove it."
"Road work ahead? Yeah I sure hope it does."
"Speed limits oppress our need for speed."
"In the end it is all about family."
"In the end it doesn't even matter."
"How do you all make whistling look so easy?"
"I hate this place. My feet hurt."
"What did my father say to me? I had headphones and I couldn't hear him."
"What a dissapointing movie. What was the hype all about?"
"I wish penguins were real."
"I think I saw a chicken cross the road. I should have stopped to ask!"
"So you’re telling me that a shrimp fried this rice?"
"Do French call “french fries” just “fries”?"
"I am going out to touch grass for a bit."
"You all need to touch grass like right now."
"I do not think my thoughts are mine."
"It would not be forbidden if it weren't interesting."
"My cat keeps knocking over the internet router."
"Ew, I stepped on a bug!"
"How can I unhear something?"
"I am definitely the funniest person alive."
"My hair isn't working today. I hope I do not run into anyone."
"Did you know sausages are 80% sugar?"
"Another day, another dollar."
"My music taste is objectively the best."
"If there's toilet paper at work there's toilet paper at home."
"How do they milk an almond anyway?"
"Crazy? I was crazy once."
"I wonder if my friends have a group chat without me."
"We just need one more road and traffic will be fixed."
"No thoughts. Head empty."
"I know where to get the best croissant in the city but I'm not telling anyone."
"I'm an adult now. I need to start liking olives."
"I still dream about you."
"Don't stop dreaming just because you had a nightmare."
"The beauty you find in ordinary things is a reflection of the beauty in you."
"Nothing beats a good nap."
"I had a dream where I was a little pig living on a farm. Oink Oink Oink."
"Why longitude shaped like an orange slice?"
"About to make this new movie my whole personality."
"Who would win? the sun or 3 billion lions?"
"Dinner's Ready! Bone apple teeth!"
"I just discovered I've been watering a plastic plant."
"I must lead a virtuous life in order to preserve the pureness of my soul."
"I don't think my boss is qualified enough to be my boss."
"Risk everything. The is no point living a life if you don't try things."
"The city keeps changing. So should you."
"For every cup of rice, add two cups of water."
"I fear anything that thinks faster than I do."
];
const usuarios = [
  "RennaZinc123",
  "RealRennaZinc",
  "xXRennaZincXx",
  "RennaZinc_official",
  "NotRennaZinc",
  "RennaZinc",
  "RennaCopper",
  "RennaAlloy",
];
